/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: validate_flight_itinerary
 * Site: google-flights
 * Intent: Validate whether a Google Flights multi-leg itinerary is accepted as searchable by the BVAT3 endpoint.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/validate_flight_itinerary/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "validate_flight_itinerary",
  "intent": {
    "description": "Validate whether a Google Flights multi-leg itinerary is accepted as searchable by the BVAT3 endpoint.",
    "userSaid": "searched for a round trip flight; searched for a one way flight; did a multi city flight query; multi city from SJC to SAN to LAX to SFO; searched for a multi city flight; dropped the 3rd leg from teh fight"
  },
  "parameters": [
    {
      "name": "itinerary",
      "type": "string",
      "description": "Ordered itinerary legs. Accepts JSON such as [{\"origin\":\"SJC\",\"destination\":\"SAN\"},{\"origin\":\"SAN\",\"destination\":\"SJC\"}] or compact text like SJC>SAN;SAN>SJC. Airport codes use type 0 and Google place ids like /m/0d9jr use type 5.",
      "default": "[{\"origin\":\"SJC\",\"destination\":\"SAN\"},{\"origin\":\"SAN\",\"destination\":\"SJC\"}]",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/batchexecute?rpcids=BVAT3&source-path=%2Ftravel%2Fflights&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/flights",
        "Accept-Language": "en-US,en;q=0.9",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "{\"itinerary\":\"${param.itinerary}\"}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights?tfs=CBwQARoSagcIARIDU0pDcgcIARIDU0FOGhJqBwgBEgNTQU5yBwgBEgNTSkNAAUgBcAGCAQsI____________AZgBAQ&tfu=KgIIAw",
    "waitUntil": "domcontentloaded",
    "waitMs": 500,
    "timeoutMs": 30000,
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "\\\"FdrFJe\\\":\\\"([^\\\"]+)\\\"",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "\\\"cfb2h\\\":\\\"([^\\\"]+)\\\"",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface ValidateFlightItineraryInput {
  /** Ordered itinerary legs. Accepts JSON such as [{"origin":"SJC","destination":"SAN"},{"origin":"SAN","destination":"SJC"}] or compact text like SJC>SAN;SAN>SJC. Airport codes use type 0 and Google place ids like /m/0d9jr use type 5. */
  itinerary?: string;
}

export async function validateFlightItinerary(
  input: ValidateFlightItineraryInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    itinerary: input.itinerary ?? "[{\"origin\":\"SJC\",\"destination\":\"SAN\"},{\"origin\":\"SAN\",\"destination\":\"SJC\"}]",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
