/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_flight_status
 * Site: southwest
 * Intent: Get Southwest flight status for a flight segment.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/get_flight_status/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_flight_status",
  "intent": {
    "description": "Get Southwest flight status for a flight segment.",
    "userSaid": "selected my upcoming flight"
  },
  "parameters": [
    {
      "name": "departure_date",
      "type": "string",
      "description": "Flight departure date in YYYY-MM-DD format.",
      "verified": false,
      "verifyNote": "waived-bot"
    },
    {
      "name": "origination_airport_code",
      "type": "string",
      "description": "Origin airport code.",
      "verified": false,
      "verifyNote": "waived-bot"
    },
    {
      "name": "destination_airport_code",
      "type": "string",
      "description": "Destination airport code.",
      "verified": false,
      "verifyNote": "waived-bot"
    },
    {
      "name": "flight_number",
      "type": "string",
      "description": "Southwest flight number.",
      "verified": false,
      "verifyNote": "waived-bot"
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "required": true,
          "capability": "ordinary_http",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\\\"]+)\"",
          "group": 1
        }
      ],
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.southwest.com/api/air-operations/v1/air-operations/api/air/flights/statuses",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "Referer": "https://www.southwest.com/air/manage-reservation/view",
        "x-api-key": "${state.southwest_api_key}",
        "x-app-id": "air-manage-reservation-v2",
        "x-app-version": "27.0.0",
        "x-channel-id": "southwest",
        "x-diagnostic": "{\"spa\":\"27.0.0\"}",
        "x-user-experience-id": "${generated.uuid}"
      },
      "body": "{\"application\":\"air-manage-reservation-v2\",\"flightStatusRequests\":[{\"departureDate\":\"${param.departure_date}\",\"destinationAirportCode\":\"${param.destination_airport_code}\",\"flightNumber\":\"${param.flight_number}\",\"originationAirportCode\":\"${param.origination_airport_code}\"}],\"site\":\"southwest\"}",
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts",
  "liveVerified": true
};

export interface GetFlightStatusInput {
  /** Flight departure date in YYYY-MM-DD format. */
  departure_date: string;
  /** Origin airport code. */
  origination_airport_code: string;
  /** Destination airport code. */
  destination_airport_code: string;
  /** Southwest flight number. */
  flight_number: string;
}

export async function getFlightStatus(
  input: GetFlightStatusInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    departure_date: input.departure_date,
    origination_airport_code: input.origination_airport_code,
    destination_airport_code: input.destination_airport_code,
    flight_number: input.flight_number,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
