/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_flight_status
 * Site: southwest
 * Intent: Get the current operating status of a Southwest flight by date, route, and flight number.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/get_flight_status/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_flight_status",
  "intent": {
    "description": "Get the current operating status of a Southwest flight by date, route, and flight number.",
    "userSaid": "Get flight status details for a Southwest flight."
  },
  "parameters": [
    {
      "name": "departure_date",
      "type": "string",
      "description": "Flight departure date in YYYY-MM-DD format. Southwest's live flight-status API supports the current operating window; use today or tomorrow.",
      "verified": true
    },
    {
      "name": "origination_airport_code",
      "type": "string",
      "description": "Origin airport code.",
      "verified": true
    },
    {
      "name": "destination_airport_code",
      "type": "string",
      "description": "Destination airport code.",
      "verified": true
    },
    {
      "name": "flight_number",
      "type": "string",
      "description": "Southwest flight number.",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/air/flight-status/path",
      "headers": {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      },
      "mode": "navigate",
      "navigation": {
        "waitUntil": "domcontentloaded",
        "timeoutMs": 60000,
        "pollIntervalMs": 100,
        "selector": "h1 span[aria-label^=\"flight number\"], [data-test=\"serviceErrorMessageBody\"]"
      },
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Historical and distant-future flight status",
      "reason": "Southwest exposes operational status only for its current operating window; use today or tomorrow."
    },
    {
      "feature": "Rendered-page transport",
      "reason": "Southwest's route-specific API represents a valid no-status combination as HTTP 400. The generated tool instead navigates the public date-and-flight-number result page and applies exact origin/destination filters to the rendered result."
    }
  ],
  "liveVerified": true
};

export interface GetFlightStatusInput {
  /** Flight departure date in YYYY-MM-DD format. Southwest's live flight-status API supports the current operating window; use today or tomorrow. */
  departure_date: string;
  /** Origin airport code. */
  origination_airport_code: string;
  /** Destination airport code. */
  destination_airport_code: string;
  /** Southwest flight number. */
  flight_number: string;
}

export async function getFlightStatus(
  input: GetFlightStatusInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    departure_date: input.departure_date,
    origination_airport_code: input.origination_airport_code,
    destination_airport_code: input.destination_airport_code,
    flight_number: input.flight_number,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
