/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: suggest_hotel_destinations
 * Site: google-hotels
 * Intent: Get Google Hotels destination and hotel autocomplete suggestions for a typed query.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/suggest_hotel_destinations/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "suggest_hotel_destinations",
  "intent": {
    "description": "Get Google Hotels destination and hotel autocomplete suggestions for a typed query.",
    "userSaid": "searched for hotels at chicago loop from july 3-6; changed location to tahoe city; searched for hotels in tahoe; searched for hotels in denver downtown"
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "Partial or full destination or hotel search text.",
      "default": "denver downtown",
      "verified": true
    },
    {
      "name": "limit",
      "type": "number",
      "description": "Maximum number of suggestions requested.",
      "default": 15,
      "verified": false,
      "verifyNote": "annotated"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=mejVKc&source-path=%2Ftravel%2Fsearch&f.sid=-7129101702754032847&bl=boq_travel-frontend-ui_20260603.00_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=3443921&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/travel/search?qs=OAA&ved=0CAAQ5JsGahcKEwiI69GMpe6UAxUAAAAAHQAAAAAQCA",
        "x-goog-ext-190139975-jspb": "[\"US\",\"ZZ\",\"DTQmiQ==\"]",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=%5B%5B%5B%22mejVKc%22%2C%22%5B%5C%22${param.query}%5C%22%2C%5C%22%5C%22%2C1%2C0%2Cnull%2C30%2C${param.limit}%5D%22%2Cnull%2C%22generic%22%5D%5D%5D&",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface SuggestHotelDestinationsInput {
  /** Partial or full destination or hotel search text. */
  query?: string;
  /** Maximum number of suggestions requested. */
  limit?: number;
}

export async function suggestHotelDestinations(
  input: SuggestHotelDestinationsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query ?? "denver downtown",
    limit: input.limit ?? 15,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
