/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: suggest_hotel_destinations
 * Site: google-hotels
 * Intent: Return ranked destination, lodging-query, and hotel suggestions for free-text input.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/suggest_hotel_destinations/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "suggest_hotel_destinations",
  "intent": {
    "description": "Return ranked destination, lodging-query, and hotel suggestions for free-text input.",
    "userSaid": "searched for hotels at chicago loop; changed location to tahoe city; searched for hotels in denver downtown"
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "Partial or complete destination, neighborhood, landmark, or property name.",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=mejVKc&source-path=%2Ftravel%2Fsearch&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/search?qs=OAA&ved=0CAAQ5JsGahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQCA",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=[[[\"mejVKc\",\"[\\\"${param.query}\\\",\\\"\\\",1,0,null,30,10]\",null,\"generic\"]]]",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "bootstrap": {
    "url": "https://www.google.com/travel/search?qs=OAA&ved=0CAAQ5JsGahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQCA",
    "waitUntil": "domcontentloaded",
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "FdrFJe(?:\\\\u0022|\\\")?\\s*:(?:\\\\u0022|\\\")(-?[0-9]+)",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "cfb2h(?:\\\\u0022|\\\")?\\s*:(?:\\\\u0022|\\\")(boq_travel-frontend-ui_[^\\\"<]+)",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Prior-query contextualization",
      "reason": "Independent live verification returned the same eight Chicago Loop suggestions in the same order for two distinct previous-query values, so the recorded argument is not exposed as a no-op public input.",
      "omittedParameters": [
        "previous_query"
      ]
    },
    {
      "feature": "Caller-controlled result limit",
      "reason": "Independent live verification returned 10 suggestions for both recorded limit 10 and requested limit 3, proving the server ignores this argument for the suggestion RPC.",
      "omittedParameters": [
        "max_results"
      ]
    },
    {
      "feature": "Suggestion mode variants",
      "reason": "One recording used internal mode 3, but no UI input or request field establishes how that variant is selected; the workflow uses the mode 1 encoding proven by the other recordings."
    }
  ],
  "liveVerified": true
};

export interface SuggestHotelDestinationsInput {
  /** Partial or complete destination, neighborhood, landmark, or property name. */
  query: string;
}

export async function suggestHotelDestinations(
  input: SuggestHotelDestinationsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
