/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: suggest_hotel_destinations
 * Site: google-hotels
 * Intent: Suggest ordered Google Hotels destinations and properties from a partial query.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/suggest_hotel_destinations/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "suggest_hotel_destinations",
  "intent": {
    "description": "Suggest ordered Google Hotels destinations and properties from a partial query.",
    "userSaid": "Searched for hotels in Chicago Loop, Tahoe City, and Denver downtown."
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "Partial destination, neighborhood, hotel, or lodging query.",
      "default": "denver downtown",
      "verified": true
    },
    {
      "name": "max_results",
      "type": "number",
      "description": "Maximum number of suggestions to request and return.",
      "default": 0,
      "verified": true
    },
    {
      "name": "limit",
      "type": "number",
      "description": "Backward-compatible alias for max_results. Zero uses the default of 15.",
      "default": 0,
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=mejVKc&source-path=%2Ftravel%2Fsearch&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/search?qs=OAA&ved=0CAAQ5JsGahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQCA",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "query=${param.query}&max_results=${param.max_results}&limit=${param.limit}",
      "bodyPlaceholderEncoding": "raw",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "bootstrap": {
    "url": "https://www.google.com/travel/search?qs=OAA&ved=0CAAQ5JsGahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQCA",
    "waitUntil": "domcontentloaded",
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "\\\"FdrFJe\\\":\\\"(-?[0-9]+)\\\"",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "\\\"cfb2h\\\":\\\"([^\\\"]+)\\\"",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Prior-search contextualization",
      "reason": "Live differential verification produced the exact same ordered suggestions for distinct recorded context strings, so this no-op input is not exposed.",
      "omittedParameters": [
        "context_query"
      ]
    },
    {
      "feature": "Autocomplete mode variants",
      "reason": "The recording showed internal RPC mode values 1 and 3 without a user-facing control; the dominant recorded autocomplete mode 1 is used."
    }
  ],
  "liveVerified": true
};

export interface SuggestHotelDestinationsInput {
  /** Partial destination, neighborhood, hotel, or lodging query. */
  query?: string;
  /** Maximum number of suggestions to request and return. */
  max_results?: number;
  /** Backward-compatible alias for max_results. Zero uses the default of 15. */
  limit?: number;
}

export async function suggestHotelDestinations(
  input: SuggestHotelDestinationsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query ?? "denver downtown",
    max_results: input.max_results ?? 0,
    limit: input.limit ?? 0,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
