/**
 * Tests for the codegen emitter (`imprint emit`). Verifies the shape of
 * the generated examples/<site>/index.ts: WORKFLOW const, Input
 * interface, exported camelCase tool function, runtime import, default
 * fallbacks. Doesn't actually execute the generated tool — that's
 * runtime.test.ts territory.
 */

import { describe, expect, it } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join as pathJoin } from 'node:path';
import { emit } from '../src/imprint/emit.ts';
import type { Workflow } from '../src/imprint/types.ts';

function withTempDir<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(pathJoin(tmpdir(), 'imprint-emit-test-'));
  try {
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function writeWorkflow(dir: string, w: Workflow): string {
  const path = pathJoin(dir, 'workflow.json');
  writeFileSync(path, JSON.stringify(w, null, 2));
  return path;
}

const MIN_WORKFLOW: Workflow = {
  toolName: 'do_thing',
  intent: { description: 'Do a thing.' },
  parameters: [
    { name: 'q', type: 'string', description: 'query' },
    { name: 'count', type: 'number', description: 'count', default: 10 },
  ],
  requests: [
    {
      method: 'GET',
      url: 'https://example.com/api/x?q=${param.q}&n=${param.count}',
      headers: {},
    },
  ],
  site: 'demo',
};

describe('emit', () => {
  it('writes examples/<site>/index.ts with the expected exports', () => {
    withTempDir((dir) => {
      const wfPath = writeWorkflow(dir, MIN_WORKFLOW);
      const result = emit({ workflowPath: wfPath, outDir: dir });

      expect(result.toolName).toBe('do_thing');
      expect(result.outPath.endsWith('/index.ts')).toBe(true);

      const source = readFileSync(result.outPath, 'utf8');

      // Generated header signals codegen + names the regenerate command.
      expect(source).toContain('GENERATED by `imprint emit`');
      expect(source).toContain('imprint emit examples/demo/workflow.json --force');

      // Workflow object inlined (so the file is self-contained).
      expect(source).toContain('"toolName": "do_thing"');

      // PascalCase Input interface; camelCase tool fn.
      expect(source).toContain('export interface DoThingInput');
      expect(source).toContain('export async function doThing(');

      // Required vs optional params reflect the schema (default → optional).
      expect(source).toMatch(/q: string;/); // required
      expect(source).toMatch(/count\?: number;/); // has default → optional

      // Re-exports the WORKFLOW constant for tool-loader discovery.
      expect(source).toContain('export { WORKFLOW }');
    });
  });

  it('refuses to overwrite an existing index.ts without --force', () => {
    withTempDir((dir) => {
      const wfPath = writeWorkflow(dir, MIN_WORKFLOW);
      emit({ workflowPath: wfPath, outDir: dir });
      expect(() => emit({ workflowPath: wfPath, outDir: dir })).toThrow(/already exists/);
    });
  });

  it('overwrites with --force', () => {
    withTempDir((dir) => {
      const wfPath = writeWorkflow(dir, MIN_WORKFLOW);
      emit({ workflowPath: wfPath, outDir: dir });
      // Sentinel — should be replaced after the second emit.
      const indexPath = pathJoin(dir, 'index.ts');
      const before = readFileSync(indexPath, 'utf8');
      writeFileSync(indexPath, '/* sentinel — should be overwritten */', 'utf8');
      emit({ workflowPath: wfPath, outDir: dir, force: true });
      const after = readFileSync(indexPath, 'utf8');
      expect(after).not.toBe('/* sentinel — should be overwritten */');
      expect(after).toBe(before);
    });
  });

  it('handles a workflow with zero parameters', () => {
    withTempDir((dir) => {
      const wf: Workflow = {
        ...MIN_WORKFLOW,
        toolName: 'no_params',
        parameters: [],
      };
      const wfPath = writeWorkflow(dir, wf);
      const r = emit({ workflowPath: wfPath, outDir: dir });
      const source = readFileSync(r.outPath, 'utf8');
      expect(source).toContain('export interface NoParamsInput');
      // No parameters → empty params block but still typechecks.
      expect(source).toContain('// (no parameters)');
    });
  });

  it("creates the output dir if it doesn't exist", () => {
    withTempDir((dir) => {
      const wfPath = writeWorkflow(dir, MIN_WORKFLOW);
      const target = pathJoin(dir, 'nested', 'output');
      const r = emit({ workflowPath: wfPath, outDir: target });
      expect(r.outPath.startsWith(target)).toBe(true);
      // No throw means the nested dir was created.
    });
  });
});
