/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_hotel_photos
 * Site: google-hotels
 * Intent: Fetch photo thumbnail URLs for a selected Google Hotels result.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/get_hotel_photos/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_hotel_photos",
  "intent": {
    "description": "Fetch photo thumbnail URLs for a selected Google Hotels result.",
    "userSaid": "clicked one of hte offerings, saw booking options"
  },
  "parameters": [
    {
      "name": "hotel_token",
      "type": "string",
      "description": "Google Hotels selected hotel token.",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "image_size",
      "type": "number",
      "description": "Requested square thumbnail size in pixels.",
      "default": 152,
      "verified": false,
      "verifyNote": "annotated"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=zM1L7d&source-path=%2Ftravel%2Fsearch&f.sid=7513562915459271421&bl=boq_travel-frontend-ui_20260527.01_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=3452256&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "x-goog-ext-190139975-jspb": "[\"US\",\"ZZ\",\"x6c25Q==\"]",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]",
        "Referer": "https://www.google.com/travel/search?q=chicago%20loop&qs=CAEgACgAMiRDaGNJNzgtbHVvWGRob2FJQVJvS0wyMHZNREoyY0dkbk1SQUI4DUgA&ved=0CAAQ5JsGahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQWg&ts=CAESCgoCCAMKAggDEAAaOwodEhkKCS9tLzBnejQ2OToMQ2hpY2FnbyBMb29wGgASGhIUCgcI6g8QBxgDEgcI6g8QBxgGGAMyAggBKgkKBToDVVNEGgA&ap=MAA",
        "Accept-Language": "en-US,en;q=0.9"
      },
      "body": "f.req=[[ [\"zM1L7d\",\"[null,null,null,[${param.image_size},${param.image_size}],\\\"${param.hotel_token}\\\"]\",null,\"1\"] ]]",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface GetHotelPhotosInput {
  /** Google Hotels selected hotel token. */
  hotel_token: string;
  /** Requested square thumbnail size in pixels. */
  image_size?: number;
}

export async function getHotelPhotos(
  input: GetHotelPhotosInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    image_size: input.image_size ?? 152,
    hotel_token: input.hotel_token,
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
