/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_account_details
 * Site: southwest
 * Intent: Get the signed-in Southwest member's account and loyalty status.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/get_account_details/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_account_details",
  "intent": {
    "description": "Get the signed-in Southwest member's account and loyalty status.",
    "userSaid": "logged into southwest"
  },
  "parameters": [],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\"]+)\"",
          "group": 1,
          "required": true,
          "capability": "ordinary_http"
        }
      ],
      "effect": "safe"
    },
    {
      "method": "GET",
      "url": "https://www.southwest.com/api/loyalty-management/v2/loyalty-management/accounts/self/customer-details-secure",
      "headers": {
        "x-api-key": "${state.southwest_api_key}",
        "x-app-id": "landing-home-page-v2",
        "x-app-version": "27.0.0",
        "x-channel-id": "southwest",
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://www.southwest.com/"
      },
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts"
};

export interface GetAccountDetailsInput {

}

export async function getAccountDetails(
  _input: GetAccountDetailsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    // (no parameters)

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
