/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: lookup_flight_locations
 * Site: google-flights
 * Intent: Search Google Flights location autocomplete for airports, cities, and travel places by text query.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/lookup_flight_locations/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "lookup_flight_locations",
  "intent": {
    "description": "Search Google Flights location autocomplete for airports, cities, and travel places by text query.",
    "userSaid": "searched for a round trip flight; multi city from SJC to SAN to LAX to SFO; searched for a multi city flight"
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "Partial or full airport, city, or place query typed by the user.",
      "default": "san di",
      "verified": true
    },
    {
      "name": "location_types",
      "type": "string",
      "description": "Optional type filter. Use default for recorded Google Flights location types, or all to include the expanded region/county type.",
      "default": "default",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/batchexecute?rpcids=H028ib&source-path=%2Ftravel%2Fflights&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&rt=c",
      "headers": {
        "X-Same-Domain": "1",
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "Referer": "https://www.google.com/travel/flights",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=${param.query}&location_types=${param.location_types}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights",
    "waitUntil": "load",
    "waitMs": 1000,
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "(?:\\\\?\"|&quot;)FdrFJe(?:\\\\?\"|&quot;)\\s*:\\s*(?:\\\\?\"|&quot;)(-?[0-9]+)",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "(?:\\\\?\"|&quot;)cfb2h(?:\\\\?\"|&quot;)\\s*:\\s*(?:\\\\?\"|&quot;)(boq_travel-frontend-flights-ui_[^\\\\\"&]+)",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface LookupFlightLocationsInput {
  /** Partial or full airport, city, or place query typed by the user. */
  query?: string;
  /** Optional type filter. Use default for recorded Google Flights location types, or all to include the expanded region/county type. */
  location_types?: string;
}

export async function lookupFlightLocations(
  input: LookupFlightLocationsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query ?? "san di",
    location_types: input.location_types ?? "default",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
