/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_flight_calendar_prices
 * Site: google-flights
 * Intent: Get round-trip date-pair fare prices for an airport route over a calendar range.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/get_flight_calendar_prices/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_flight_calendar_prices",
  "intent": {
    "description": "Get round-trip date-pair fare prices for an airport route over a calendar range.",
    "userSaid": "searched for a round trip flight"
  },
  "parameters": [
    {
      "name": "trip_type",
      "type": "string",
      "description": "Calendar mode; only round_trip is supported by the recorded API encoding.",
      "default": "round_trip",
      "verified": true
    },
    {
      "name": "origin",
      "type": "string",
      "description": "Three-letter origin airport code.",
      "verified": true
    },
    {
      "name": "destination",
      "type": "string",
      "description": "Three-letter destination airport code.",
      "verified": true
    },
    {
      "name": "start_date",
      "type": "string",
      "description": "Inclusive beginning of the departure-date range in YYYY-MM-DD format.",
      "verified": true
    },
    {
      "name": "end_date",
      "type": "string",
      "description": "Inclusive end of the departure-date range in YYYY-MM-DD format.",
      "verified": true
    },
    {
      "name": "trip_length_days",
      "type": "number",
      "description": "Exact round-trip length in days.",
      "verified": true
    },
    {
      "name": "adults",
      "type": "number",
      "description": "Number of adult passengers.",
      "default": 1,
      "verified": true
    },
    {
      "name": "cabin_class",
      "type": "string",
      "description": "Cabin class; only economy is supported by the recorded API encoding.",
      "default": "economy",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/travel.frontend.flights.FlightsFrontendService/GetCalendarPicker?f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]",
        "Referer": "https://www.google.com/travel/flights"
      },
      "body": "f.req=${param.trip_type}|${param.origin}|${param.destination}|${param.start_date}|${param.end_date}|${param.trip_length_days}|${param.adults}|${param.cabin_class}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights",
    "waitUntil": "domcontentloaded",
    "timeoutMs": 30000,
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "[\"']FdrFJe[\"']\\s*:\\s*[\"'](-?\\d+)[\"']",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "[\"']cfb2h[\"']\\s*:\\s*[\"']([^\"']+)[\"']",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Trip modes",
      "reason": "Seq 97 records only the round-trip enum and reciprocal two-leg shape; one-way encoding is intentionally not guessed.",
      "omittedParameters": []
    },
    {
      "feature": "Cabin classes",
      "reason": "Seq 97 establishes only enum 1 (economy); other cabin enum mappings are not evidenced.",
      "omittedParameters": []
    },
    {
      "feature": "Location identifiers",
      "reason": "Seq 97 establishes three-letter airport codes, not arbitrary city or region identifiers.",
      "omittedParameters": []
    }
  ],
  "liveVerified": true
};

export interface GetFlightCalendarPricesInput {
  /** Calendar mode; only round_trip is supported by the recorded API encoding. */
  trip_type?: string;
  /** Three-letter origin airport code. */
  origin: string;
  /** Three-letter destination airport code. */
  destination: string;
  /** Inclusive beginning of the departure-date range in YYYY-MM-DD format. */
  start_date: string;
  /** Inclusive end of the departure-date range in YYYY-MM-DD format. */
  end_date: string;
  /** Exact round-trip length in days. */
  trip_length_days: number;
  /** Number of adult passengers. */
  adults?: number;
  /** Cabin class; only economy is supported by the recorded API encoding. */
  cabin_class?: string;
}

export async function getFlightCalendarPrices(
  input: GetFlightCalendarPricesInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    trip_type: input.trip_type ?? "round_trip",
    adults: input.adults ?? 1,
    cabin_class: input.cabin_class ?? "economy",
    origin: input.origin,
    destination: input.destination,
    start_date: input.start_date,
    end_date: input.end_date,
    trip_length_days: input.trip_length_days,
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
