/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: list_hotel_booking_options
 * Site: google-hotels
 * Intent: List booking providers and prices for a selected Google Hotels stay.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/list_hotel_booking_options/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "list_hotel_booking_options",
  "intent": {
    "description": "List booking providers and prices for a selected Google Hotels stay.",
    "userSaid": "clicked one of hte offerings, saw booking options; changed to stay total pricing; looked at more booking options"
  },
  "parameters": [
    {
      "name": "hotel_token",
      "type": "string",
      "description": "Google Hotels selected hotel token.",
      "verified": true
    },
    {
      "name": "check_in_date",
      "type": "string",
      "description": "Check-in date in YYYY-MM-DD format.",
      "default": "2026-08-03",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "check_out_date",
      "type": "string",
      "description": "Check-out date in YYYY-MM-DD format.",
      "default": "2026-08-06",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "adults",
      "type": "number",
      "description": "Number of adult travelers.",
      "default": 3,
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "children",
      "type": "number",
      "description": "Number of child travelers if included.",
      "default": 1,
      "verified": false,
      "verifyNote": "annotated"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=M0CRd&source-path=%2Ftravel%2Fsearch&f.sid=7513562915459271421&bl=boq_travel-frontend-ui_20260527.01_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=3552256&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/travel/search?q=chicago%20loop",
        "x-goog-ext-190139975-jspb": "[\"US\",\"ZZ\",\"x6c25Q==\"]",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=${param.hotel_token}|${param.check_in_date}|${param.check_out_date}|${param.adults}|${param.children}|USD|nightly|&",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface ListHotelBookingOptionsInput {
  /** Google Hotels selected hotel token. */
  hotel_token: string;
  /** Check-in date in YYYY-MM-DD format. */
  check_in_date?: string;
  /** Check-out date in YYYY-MM-DD format. */
  check_out_date?: string;
  /** Number of adult travelers. */
  adults?: number;
  /** Number of child travelers if included. */
  children?: number;
}

export async function listHotelBookingOptions(
  input: ListHotelBookingOptionsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    hotel_token: input.hotel_token,
    check_in_date: input.check_in_date ?? "2026-08-03",
    check_out_date: input.check_out_date ?? "2026-08-06",
    adults: input.adults ?? 3,
    children: input.children ?? 1,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
