/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: search_google_hotels
 * Site: google-hotels
 * Intent: Search Google Hotels for lodging in a destination over a given date range and party composition, returning the list of nearby hotels with star rating, guest rating, nightly + total prices, and Google identifiers.
 *
 * To regenerate: imprint emit examples/google-hotels/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from '../../../src/imprint/runtime.ts';
import type { ToolResult, Workflow } from '../../../src/imprint/types.ts';

const WORKFLOW: Workflow = {
  "toolName": "search_google_hotels",
  "intent": {
    "description": "Search Google Hotels for lodging in a destination over a given date range and party composition, returning the list of nearby hotels with star rating, guest rating, nightly + total prices, and Google identifiers.",
    "userSaid": "i just searched for htoels in tahoe city from june 19 to june 27 for 2 people | i added some adutls and some children | i clicked one of hte hotels | i clicked hte box that shows the stay total price (not nightly prices before taxes and fees) | i played around with all the filters | i played around with the brands"
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "Free-text destination query the user typed into the search box (e.g. 'tahoe city').",
      "default": "tahoe city"
    },
    {
      "name": "place_mid",
      "type": "string",
      "description": "Google Knowledge Graph machine ID for the destination (the '/m/0gyvmkl' style identifier returned by the autocomplete request). Required to anchor the search to a specific place.",
      "default": "/m/0gyvmkl"
    },
    {
      "name": "place_ftid",
      "type": "string",
      "description": "Google Maps feature ID for the destination, of the form '0xHEX:0xHEX'. Comes from the autocomplete response alongside the place_mid.",
      "default": "0x809bd62ecf1fa721:0x2a98b230816c9ed1"
    },
    {
      "name": "place_name",
      "type": "string",
      "description": "Display name for the destination (e.g. 'Tahoe City').",
      "default": "Tahoe City"
    },
    {
      "name": "check_in_year",
      "type": "number",
      "description": "Check-in year (e.g. 2026).",
      "default": 2026
    },
    {
      "name": "check_in_month",
      "type": "number",
      "description": "Check-in month (1–12).",
      "default": 6
    },
    {
      "name": "check_in_day",
      "type": "number",
      "description": "Check-in day of month (1–31).",
      "default": 19
    },
    {
      "name": "check_out_year",
      "type": "number",
      "description": "Check-out year.",
      "default": 2026
    },
    {
      "name": "check_out_month",
      "type": "number",
      "description": "Check-out month (1–12).",
      "default": 6
    },
    {
      "name": "check_out_day",
      "type": "number",
      "description": "Check-out day of month (1–31).",
      "default": 27
    },
    {
      "name": "nights",
      "type": "number",
      "description": "Length of stay in nights. Must equal check_out - check_in.",
      "default": 8
    },
    {
      "name": "child_age_1",
      "type": "number",
      "description": "Age of the first child (omit by leaving default; the workflow currently always sends two children to mirror the recorded request).",
      "default": 3
    },
    {
      "name": "child_age_2",
      "type": "number",
      "description": "Age of the second child.",
      "default": 3
    },
    {
      "name": "currency",
      "type": "string",
      "description": "ISO currency code for displayed prices.",
      "default": "USD"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=AtySUc&source-path=%2Ftravel%2Fsearch&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Origin": "https://www.google.com",
        "Referer": "https://www.google.com/travel/search?q=${param.query}",
        "Accept-Language": "en-US,en;q=0.9",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"${param.currency}\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=%5B%5B%5B%22AtySUc%22%2C%22%5B%5C%22${param.query}%5C%22%2C%5B1%2C%5B%5B%5B${param.child_age_1}%5D%2C%5B${param.child_age_2}%5D%5D%2C0%5D%2C%5B%5Bnull%2C%5B%5B%5C%22${param.place_mid}%5C%22%2Cnull%2Cnull%2Cnull%2Cnull%2C%5C%22${param.place_ftid}%5C%22%2C%5C%22${param.place_name}%5C%22%5D%5D%2C%5B%5D%5D%2C%5Bnull%2C%5B%5B${param.check_in_year}%2C${param.check_in_month}%2C${param.check_in_day}%5D%2C%5B${param.check_out_year}%2C${param.check_out_month}%2C${param.check_out_day}%5D%2C${param.nights}%5D%2Cnull%2Cnull%2Cnull%2C%5B1%5D%5D%5D%2Cnull%2C%5B%5Bnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C%5C%22${param.currency}%5C%22%5D%2Cnull%2C%5B%5D%5D%5D%2C%5B1%2Cnull%2Cnull%2C0%2C0%2Cnull%2C13%2Cnull%2C0%5D%5D%22%2Cnull%2C%221%22%5D%5D%5D&"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts"
};

export interface SearchGoogleHotelsInput {
  /** Free-text destination query the user typed into the search box (e.g. 'tahoe city'). */
  query?: string;
  /** Google Knowledge Graph machine ID for the destination (the '/m/0gyvmkl' style identifier returned by the autocomplete request). Required to anchor the search to a specific place. */
  place_mid?: string;
  /** Google Maps feature ID for the destination, of the form '0xHEX:0xHEX'. Comes from the autocomplete response alongside the place_mid. */
  place_ftid?: string;
  /** Display name for the destination (e.g. 'Tahoe City'). */
  place_name?: string;
  /** Check-in year (e.g. 2026). */
  check_in_year?: number;
  /** Check-in month (1–12). */
  check_in_month?: number;
  /** Check-in day of month (1–31). */
  check_in_day?: number;
  /** Check-out year. */
  check_out_year?: number;
  /** Check-out month (1–12). */
  check_out_month?: number;
  /** Check-out day of month (1–31). */
  check_out_day?: number;
  /** Length of stay in nights. Must equal check_out - check_in. */
  nights?: number;
  /** Age of the first child (omit by leaving default; the workflow currently always sends two children to mirror the recorded request). */
  child_age_1?: number;
  /** Age of the second child. */
  child_age_2?: number;
  /** ISO currency code for displayed prices. */
  currency?: string;
}

export async function searchGoogleHotels(
  input: SearchGoogleHotelsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query ?? "tahoe city",
    place_mid: input.place_mid ?? "/m/0gyvmkl",
    place_ftid: input.place_ftid ?? "0x809bd62ecf1fa721:0x2a98b230816c9ed1",
    place_name: input.place_name ?? "Tahoe City",
    check_in_year: input.check_in_year ?? 2026,
    check_in_month: input.check_in_month ?? 6,
    check_in_day: input.check_in_day ?? 19,
    check_out_year: input.check_out_year ?? 2026,
    check_out_month: input.check_out_month ?? 6,
    check_out_day: input.check_out_day ?? 27,
    nights: input.nights ?? 8,
    child_age_1: input.child_age_1 ?? 3,
    child_age_2: input.child_age_2 ?? 3,
    currency: input.currency ?? "USD",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
