/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: list_upcoming_trips
 * Site: southwest
 * Intent: List upcoming Southwest trips for the logged-in account.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/list_upcoming_trips/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "list_upcoming_trips",
  "intent": {
    "description": "List upcoming Southwest trips for the logged-in account.",
    "userSaid": "logged into southwest; went to My Trips page"
  },
  "parameters": [],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "required": true,
          "capability": "ordinary_http",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\"]+)\"",
          "group": 1
        }
      ],
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.southwest.com/api/security/v4/security/token",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/x-www-form-urlencoded",
        "Referer": "https://www.southwest.com/",
        "x-app-id": "landing-home-page-v2",
        "x-app-version": "27.0.0",
        "x-channel-id": "southwest",
        "x-diagnostic": "{\"spa\":\"27.0.0\"}",
        "x-user-experience-id": "${generated.uuid}",
        "x-api-key": "${state.southwest_api_key}",
        "Origin": "https://www.southwest.com"
      },
      "body": "username=${credential.username}&password=${credential.password}&scope=openid&response_type=id_token+swa_token&client_id=6b6199ac-6726-4642-b5bd-86eb07062161",
      "captures": [
        {
          "name": "access_token",
          "required": true,
          "capability": "ordinary_http",
          "source": "json",
          "path": "$.access_token"
        },
        {
          "name": "id_token",
          "required": true,
          "capability": "ordinary_http",
          "source": "json",
          "path": "$.id_token"
        }
      ],
      "effect": "safe"
    },
    {
      "method": "GET",
      "url": "https://www.southwest.com/api/loyalty-management/v2/loyalty-management/accounts/self/future-air-reservations-secure",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://www.southwest.com/",
        "x-app-id": "landing-home-page-v2",
        "x-app-version": "27.0.0",
        "x-channel-id": "southwest",
        "x-diagnostic": "{\"spa\":\"27.0.0\"}",
        "x-user-experience-id": "${generated.uuid}",
        "x-api-key": "${state.southwest_api_key}"
      },
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts",
  "liveVerified": false,
  "liveVerifiedWaiver": {
    "kind": "waived-bot",
    "firstError": "FORBIDDEN in 385ms — escalating",
    "exhaustedBackends": [
      "fetch",
      "cdp-replay",
      "stealth-fetch"
    ]
  }
};

export interface ListUpcomingTripsInput {

}

export async function listUpcomingTrips(
  _input: ListUpcomingTripsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    // (no parameters)

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
