/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: search_flights
 * Site: google-flights
 * Intent: Search Google Flights for one-way itineraries with passenger and recorded filter controls.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/search_flights/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "search_flights",
  "intent": {
    "description": "Search Google Flights for one-way itineraries with passenger and recorded filter controls.",
    "userSaid": "searched for flights and played with stops, bags, price, time, and duration filters"
  },
  "parameters": [
    {
      "name": "trip_type",
      "type": "string",
      "description": "Only one_way is supported by this emitted search tool.",
      "default": "one_way"
    },
    {
      "name": "legs",
      "type": "string",
      "description": "A single origin,destination,YYYY-MM-DD flight leg."
    },
    {
      "name": "adults",
      "type": "number",
      "description": "Adult passengers.",
      "default": 1
    },
    {
      "name": "children",
      "type": "number",
      "description": "Child passengers.",
      "default": 0
    },
    {
      "name": "cabin_class",
      "type": "string",
      "description": "Only economy is supported by the recording.",
      "default": "economy"
    },
    {
      "name": "max_stops",
      "type": "number",
      "description": "Maximum stops per leg; 0 means unrestricted.",
      "default": 0
    },
    {
      "name": "airlines",
      "type": "string",
      "description": "Comma-separated airline codes to include.",
      "default": ""
    },
    {
      "name": "alliances",
      "type": "string",
      "description": "Comma-separated alliance codes: ONEWORLD, SKYTEAM, or STAR_ALLIANCE.",
      "default": ""
    },
    {
      "name": "carry_on_bags",
      "type": "number",
      "description": "Only 0 is supported by the recording.",
      "default": 0
    },
    {
      "name": "max_price",
      "type": "number",
      "description": "Maximum total fare; 0 means unrestricted.",
      "default": 0
    },
    {
      "name": "outbound_time_range",
      "type": "string",
      "description": "departure_start,departure_end,arrival_start,arrival_end; each hour must be an integer from 0 through 23.",
      "default": ""
    },
    {
      "name": "max_duration_minutes",
      "type": "number",
      "description": "Maximum itinerary duration; 0 means unrestricted.",
      "default": 0
    },
    {
      "name": "sort_order",
      "type": "string",
      "description": "best, price, departure_time, arrival_time, or duration.",
      "default": "best"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/travel.frontend.flights.FlightsFrontendService/GetShoppingResults?f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "Referer": "https://www.google.com/travel/flights/search?tfs=CBwQAhoeEgoyMDI2LTA2LTA4agcIARIDU0pDcgcIARIDU0FOGh4SCjIwMjYtMDYtMTFqBwgBEgNTQU5yBwgBEgNTSkNAAUgBcAGCAQsI____________AZgBAQ",
        "X-Same-Domain": "1",
        "sec-ch-ua-full-version": "\"148.0.7778.96\"",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "trip_type=${param.trip_type}&legs=${param.legs}&adults=${param.adults}&children=${param.children}&cabin_class=${param.cabin_class}&max_stops=${param.max_stops}&airlines=${param.airlines}&alliances=${param.alliances}&carry_on_bags=${param.carry_on_bags}&max_price=${param.max_price}&outbound_time_range=${param.outbound_time_range}&max_duration_minutes=${param.max_duration_minutes}&sort_order=${param.sort_order}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights/search?tfs=CBwQAhoeEgoyMDI2LTA2LTA4agcIARIDU0pDcgcIARIDU0FOGh4SCjIwMjYtMDYtMTFqBwgBEgNTQU5yBwgBEgNTSkNAAUgBcAGCAQsI____________AZgBAQ",
    "waitUntil": "domcontentloaded",
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "FdrFJe[^0-9-]{1,40}(-?[0-9]{10,})",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "(boq_travel-frontend-flights-ui_[A-Za-z0-9_.-]+)",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Price currency selection",
      "reason": "The recorded shopping contract requires the static USD page metadata header and provides no grounded request position for varying currency independently.",
      "omittedParameters": [
        "currency"
      ]
    },
    {
      "feature": "Non-economy cabin classes",
      "reason": "The recordings and live verification ground economy only.",
      "omittedParameters": []
    },
    {
      "feature": "Carry-on bag filtering",
      "reason": "The recorded field did not produce a discriminating live result, so only the unfiltered value 0 is supported.",
      "omittedParameters": []
    },
    {
      "feature": "Infant passenger mixes",
      "reason": "The recording did not exercise infant passenger changes, and live differentials produced incomplete carrier results without passenger-adjusted fares.",
      "omittedParameters": [
        "infants_in_seat",
        "infants_on_lap"
      ]
    },
    {
      "feature": "Exhaustive server-side price discovery",
      "reason": "Google's recorded server price slot can omit cheaper baseline itineraries at restrictive caps, so max_price is enforced as a deterministic postcondition over the returned result set.",
      "omittedParameters": []
    },
    {
      "feature": "Round-trip and multi-city staged search",
      "reason": "The emitted producer currently proves complete one-way selections only. Use get_flight_calendar_prices for round-trip price discovery; later-leg staged selection remains user-assisted.",
      "omittedParameters": [
        "return_time_range"
      ]
    }
  ]
};

export interface SearchFlightsInput {
  /** Only one_way is supported by this emitted search tool. */
  trip_type?: string;
  /** A single origin,destination,YYYY-MM-DD flight leg. */
  legs: string;
  /** Adult passengers. */
  adults?: number;
  /** Child passengers. */
  children?: number;
  /** Only economy is supported by the recording. */
  cabin_class?: string;
  /** Maximum stops per leg; 0 means unrestricted. */
  max_stops?: number;
  /** Comma-separated airline codes to include. */
  airlines?: string;
  /** Comma-separated alliance codes: ONEWORLD, SKYTEAM, or STAR_ALLIANCE. */
  alliances?: string;
  /** Only 0 is supported by the recording. */
  carry_on_bags?: number;
  /** Maximum total fare; 0 means unrestricted. */
  max_price?: number;
  /** departure_start,departure_end,arrival_start,arrival_end; each hour must be an integer from 0 through 23. */
  outbound_time_range?: string;
  /** Maximum itinerary duration; 0 means unrestricted. */
  max_duration_minutes?: number;
  /** best, price, departure_time, arrival_time, or duration. */
  sort_order?: string;
}

export async function searchFlights(
  input: SearchFlightsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    trip_type: input.trip_type ?? "one_way",
    adults: input.adults ?? 1,
    children: input.children ?? 0,
    cabin_class: input.cabin_class ?? "economy",
    max_stops: input.max_stops ?? 0,
    airlines: input.airlines ?? "",
    alliances: input.alliances ?? "",
    carry_on_bags: input.carry_on_bags ?? 0,
    max_price: input.max_price ?? 0,
    outbound_time_range: input.outbound_time_range ?? "",
    max_duration_minutes: input.max_duration_minutes ?? 0,
    sort_order: input.sort_order ?? "best",
    legs: input.legs,
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
