/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_travel_area_boundaries
 * Site: google-hotels
 * Intent: Get geographic boundary shapes and the canonical center for a resolved Google hotel destination.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/get_travel_area_boundaries/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_travel_area_boundaries",
  "intent": {
    "description": "Get geographic boundary shapes and the canonical center for a resolved Google hotel destination.",
    "userSaid": "searched for hotels at chicago loop; changed location to tahoe city; searched for hotels in denver downtown"
  },
  "parameters": [
    {
      "name": "destination_id",
      "type": "string",
      "description": "Resolved Google place or destination identifier.",
      "default": "",
      "verified": true
    },
    {
      "name": "place_id",
      "type": "string",
      "description": "Backward-compatible alias for destination_id.",
      "default": "/m/0525427",
      "verified": true
    },
    {
      "name": "latitude",
      "type": "number",
      "description": "Backward-compatible ignored center hint; Google resolves the canonical center from the destination ID.",
      "default": 39.746510799999996,
      "verified": true
    },
    {
      "name": "longitude",
      "type": "number",
      "description": "Backward-compatible ignored center hint; Google resolves the canonical center from the destination ID.",
      "default": -104.99250459999999,
      "verified": true
    },
    {
      "name": "detail_level",
      "type": "string",
      "description": "Boundary scale preset: all, local, detailed, or regional.",
      "default": "all",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=FCE32b&source-path=%2Ftravel%2Fsearch&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/search",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "transform-input=${param.destination_id}|${param.place_id}|${param.latitude}|${param.longitude}|${param.detail_level}",
      "bodyPlaceholderEncoding": "raw"
    }
  ],
  "site": "google-hotels",
  "bootstrap": {
    "url": "https://www.google.com/travel/search?q=chicago%20loop&qs=CAAgACgA&ved=0CAAQ8IAIahcKEwjg5tj6uN-UAxUAAAAAHQAAAAAQHQ&ts=CAEqBwoFOgNVU0Q&ap=MAA",
    "waitUntil": "domcontentloaded",
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "FdrFJe[^0-9-]{1,20}(-?[0-9]{10,})",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "cfb2h[^A-Za-z0-9_]{1,20}(boq_travel-frontend-ui_[A-Za-z0-9._-]+)",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "caller-supplied destination center",
      "reason": "Live differential verification changed latitude and longitude independently by one degree, but FCE32b returned identical Tahoe canonical center and boundary geometry; the endpoint resolves its center from destination_id.",
      "omittedParameters": [
        "latitude",
        "longitude"
      ]
    }
  ],
  "liveVerified": true
};

export interface GetTravelAreaBoundariesInput {
  /** Resolved Google place or destination identifier. */
  destination_id?: string;
  /** Backward-compatible alias for destination_id. */
  place_id?: string;
  /** Backward-compatible ignored center hint; Google resolves the canonical center from the destination ID. */
  latitude?: number;
  /** Backward-compatible ignored center hint; Google resolves the canonical center from the destination ID. */
  longitude?: number;
  /** Boundary scale preset: all, local, detailed, or regional. */
  detail_level?: string;
}

export async function getTravelAreaBoundaries(
  input: GetTravelAreaBoundariesInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    destination_id: input.destination_id ?? "",
    place_id: input.place_id ?? "/m/0525427",
    latitude: input.latitude ?? 39.746510799999996,
    longitude: input.longitude ?? -104.99250459999999,
    detail_level: input.detail_level ?? "all",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
