/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_travel_area_boundaries
 * Site: google-hotels
 * Intent: Fetch map boundary or area geometry data for a Google Hotels destination.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/get_travel_area_boundaries/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_travel_area_boundaries",
  "intent": {
    "description": "Fetch map boundary or area geometry data for a Google Hotels destination.",
    "userSaid": "searched for hotels at chicago loop from july 3-6; changed location to tahoe city; searched for hotels in denver downtown"
  },
  "parameters": [
    {
      "name": "place_id",
      "type": "string",
      "description": "Google place or knowledge graph ID for the destination.",
      "default": "/m/0525427",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "latitude",
      "type": "number",
      "description": "Latitude for the destination center.",
      "default": 39.746510799999996,
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "longitude",
      "type": "number",
      "description": "Longitude for the destination center.",
      "default": -104.99250459999999,
      "verified": false,
      "verifyNote": "annotated"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=FCE32b&source-path=%2Ftravel%2Fsearch&f.sid=-7129101702754032847&bl=boq_travel-frontend-ui_20260603.00_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=3643921&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/search?q=denver%20downtown&qs=CAAgACgA&ved=0CAAQ8IAIahcKEwiI69GMpe6UAxUAAAAAHQAAAAAQMA&ts=CAESCgoCCAMKAggDEAAqBwoFOgNVU0Q&ap=MAA",
        "Accept-Language": "en-US,en;q=0.9",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
        "x-goog-ext-190139975-jspb": "[\"US\",\"ZZ\",\"DTQmiQ==\"]",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=[[[\"FCE32b\",\"[null,[[1,15],[1,30],[2,15],[2,30],[2,60],[2,120]],null,[[[\\\"${param.place_id}\\\"],[${param.latitude},${param.longitude}]]]]\",null,\"generic\"]]]&",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface GetTravelAreaBoundariesInput {
  /** Google place or knowledge graph ID for the destination. */
  place_id?: string;
  /** Latitude for the destination center. */
  latitude?: number;
  /** Longitude for the destination center. */
  longitude?: number;
}

export async function getTravelAreaBoundaries(
  input: GetTravelAreaBoundariesInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    place_id: input.place_id ?? "/m/0525427",
    latitude: input.latitude ?? 39.746510799999996,
    longitude: input.longitude ?? -104.99250459999999,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
