/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_hotel_details
 * Site: google-hotels
 * Intent: Fetch detailed Google Hotels information for a selected hotel or vacation-rental result.
 *
 * To regenerate: imprint emit ~/.imprint/google-hotels/get_hotel_details/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_hotel_details",
  "intent": {
    "description": "Fetch detailed Google Hotels information for a selected hotel or vacation-rental result.",
    "userSaid": "clicked one of hte offerings, saw booking options; changed property type to vacation rentals instead of hotels; changed location to tahoe city"
  },
  "parameters": [
    {
      "name": "hotel_token",
      "type": "string",
      "description": "Google Hotels selected result token for the hotel, usually emitted by a hotel search result.",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "destination",
      "type": "string",
      "description": "Destination context used when opening the hotel result.",
      "default": "tahoe city",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "check_in_date",
      "type": "string",
      "description": "Check-in date in YYYY-MM-DD format.",
      "default": "2026-08-09",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "check_out_date",
      "type": "string",
      "description": "Check-out date in YYYY-MM-DD format.",
      "default": "2026-08-16",
      "verified": false,
      "verifyNote": "annotated"
    },
    {
      "name": "property_type",
      "type": "string",
      "description": "Property type context, either hotels or vacation_rentals.",
      "default": "vacation_rentals",
      "verified": true
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/TravelFrontendUi/data/batchexecute?rpcids=AtySUc&source-path=%2Ftravel%2Fsearch&f.sid=7513562915459271421&bl=boq_travel-frontend-ui_20260527.01_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/travel/search?q=${param.destination}",
        "x-goog-ext-190139975-jspb": "[\"US\",\"ZZ\",\"x6c25Q==\"]",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=${param.destination}|${param.check_in_date}|${param.check_out_date}|${param.property_type}|${param.hotel_token}",
      "effect": "safe"
    }
  ],
  "site": "google-hotels",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface GetHotelDetailsInput {
  /** Google Hotels selected result token for the hotel, usually emitted by a hotel search result. */
  hotel_token: string;
  /** Destination context used when opening the hotel result. */
  destination?: string;
  /** Check-in date in YYYY-MM-DD format. */
  check_in_date?: string;
  /** Check-out date in YYYY-MM-DD format. */
  check_out_date?: string;
  /** Property type context, either hotels or vacation_rentals. */
  property_type?: string;
}

export async function getHotelDetails(
  input: GetHotelDetailsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    destination: input.destination ?? "tahoe city",
    check_in_date: input.check_in_date ?? "2026-08-09",
    check_out_date: input.check_out_date ?? "2026-08-16",
    property_type: input.property_type ?? "vacation_rentals",
    hotel_token: input.hotel_token,
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
