/** `imprint emit` — generate <assetRoot>/<site>/<toolName>/index.ts: a thin wrapper
 *  around runtime.executeWorkflow with the workflow JSON embedded inline. */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join as pathJoin, resolve as pathResolve } from 'node:path';
import { loadJsonFile } from './load-json.ts';
import { ensureImprintRuntimeLink } from './runtime-link.ts';
import { type Workflow, WorkflowSchema } from './types.ts';

interface EmitOptions {
  /** Path to workflow.json */
  workflowPath: string;
  /** Output dir; defaults to dirname(workflowPath). File: <outDir>/index.ts. */
  outDir?: string;
  /** Overwrite an existing index.ts. Default false. */
  force?: boolean;
}

interface EmitResult {
  workflowPath: string;
  outPath: string;
  toolName: string;
  /** Summary of the parameters the generated tool accepts. */
  parameters: Workflow['parameters'];
}

export function emit(opts: EmitOptions): EmitResult {
  const workflow = loadJsonFile(
    opts.workflowPath,
    WorkflowSchema,
    {
      notFound: '→ run `imprint generate <session>` to create one.',
      badSchema:
        '→ regenerate with `imprint generate <session>` (the LLM may have produced bad output).',
    },
    'workflow.json',
  );

  const outDir = opts.outDir ?? defaultOutDir(opts.workflowPath, workflow);

  mkdirSync(outDir, { recursive: true });
  const outPath = pathJoin(outDir, 'index.ts');

  if (existsSync(outPath) && !opts.force) {
    throw new Error(
      `${outPath} already exists. Pass --force to overwrite, or move/delete the existing file first.`,
    );
  }

  // Ensure IMPRINT_HOME has a node_modules/imprint symlink so generated
  // tools can `import 'imprint/runtime'` via standard module resolution.
  // discoverTools also calls this at runtime so dangling links self-heal
  // without re-emitting.
  ensureImprintRuntimeLink(pathResolve(outDir, '..', '..'));

  const source = renderModule(workflow);
  writeFileSync(outPath, source, 'utf8');

  return {
    workflowPath: opts.workflowPath,
    outPath,
    toolName: workflow.toolName,
    parameters: workflow.parameters,
  };
}

function defaultOutDir(workflowPath: string, workflow: Workflow): string {
  const workflowDir = pathResolve(dirname(workflowPath));
  if (basename(workflowDir) === workflow.toolName) return workflowDir;
  return pathJoin(workflowDir, workflow.toolName);
}

function renderModule(workflow: Workflow): string {
  const paramTypeFields = workflow.parameters
    .map((p) => {
      const optional = p.default !== undefined ? '?' : '';
      return `  /** ${escapeJsdoc(p.description)} */\n  ${p.name}${optional}: ${p.type};`;
    })
    .join('\n');

  const defaultsBlock = workflow.parameters
    .filter((p) => p.default !== undefined)
    .map((p) => `    ${p.name}: input.${p.name} ?? ${JSON.stringify(p.default)},`)
    .join('\n');

  const requiredCopies = workflow.parameters
    .filter((p) => p.default === undefined)
    .map((p) => `    ${p.name}: input.${p.name},`)
    .join('\n');

  const workflowJson = JSON.stringify(workflow, null, 2);

  return `/**
 * GENERATED by \`imprint emit\` — DO NOT EDIT BY HAND.
 *
 * Tool: ${workflow.toolName}
 * Site: ${workflow.site}
 * Intent: ${workflow.intent.description}
 *
 * To regenerate: imprint emit ~/.imprint/${workflow.site}/${workflow.toolName}/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = ${workflowJson};

export interface ${pascalCase(workflow.toolName)}Input {
${paramTypeFields}
}

export async function ${camelCase(workflow.toolName)}(
  ${workflow.parameters.length === 0 ? '_input' : 'input'}: ${pascalCase(workflow.toolName)}Input,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
${defaultsBlock || requiredCopies || '    // (no parameters)'}
${defaultsBlock && requiredCopies ? requiredCopies : ''}
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
`;
}

function pascalCase(s: string): string {
  return s
    .split(/[_-]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join('');
}

function camelCase(s: string): string {
  const pc = pascalCase(s);
  return pc.charAt(0).toLowerCase() + pc.slice(1);
}

function escapeJsdoc(s: string): string {
  return s.replace(/\*\//g, '*\\/');
}
