/** `imprint emit` — generate examples/<site>/index.ts: a thin wrapper
 *  around runtime.executeWorkflow with the workflow JSON embedded inline. */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join as pathJoin, resolve as pathResolve, relative } from 'node:path';
import { type Workflow, WorkflowSchema } from './types.ts';

export interface EmitOptions {
  /** Path to workflow.json */
  workflowPath: string;
  /** Output dir; defaults to dirname(workflowPath). File: <outDir>/index.ts. */
  outDir?: string;
  /** Overwrite an existing index.ts. Default false. */
  force?: boolean;
}

export interface EmitResult {
  workflowPath: string;
  outPath: string;
  toolName: string;
  /** Summary of the parameters the generated tool accepts. */
  parameters: Workflow['parameters'];
}

export function emit(opts: EmitOptions): EmitResult {
  const raw = JSON.parse(readFileSync(opts.workflowPath, 'utf8'));
  const workflow = WorkflowSchema.parse(raw);

  const outDir = opts.outDir ?? pathResolve(dirname(opts.workflowPath));

  mkdirSync(outDir, { recursive: true });
  const outPath = pathJoin(outDir, 'index.ts');

  if (existsSync(outPath) && !opts.force) {
    throw new Error(
      `${outPath} already exists. Pass --force to overwrite, or move/delete the existing file first.`,
    );
  }

  // Generated files live in examples/<site>/, two levels deep from src/imprint/.
  const runtimeModule = pathResolve(import.meta.dir, 'runtime.ts');
  const importPath = relative(outDir, runtimeModule);

  const source = renderModule(workflow, importPath);
  writeFileSync(outPath, source, 'utf8');

  return {
    workflowPath: opts.workflowPath,
    outPath,
    toolName: workflow.toolName,
    parameters: workflow.parameters,
  };
}

function renderModule(workflow: Workflow, runtimeImportPath: string): string {
  const paramTypeFields = workflow.parameters
    .map((p) => {
      const optional = p.default !== undefined ? '?' : '';
      return `  /** ${escapeJsdoc(p.description)} */\n  ${p.name}${optional}: ${p.type};`;
    })
    .join('\n');

  const defaultsBlock = workflow.parameters
    .filter((p) => p.default !== undefined)
    .map((p) => `    ${p.name}: input.${p.name} ?? ${JSON.stringify(p.default)},`)
    .join('\n');

  const requiredCopies = workflow.parameters
    .filter((p) => p.default === undefined)
    .map((p) => `    ${p.name}: input.${p.name},`)
    .join('\n');

  const workflowJson = JSON.stringify(workflow, null, 2);

  return `/**
 * GENERATED by \`imprint emit\` — DO NOT EDIT BY HAND.
 *
 * Tool: ${workflow.toolName}
 * Site: ${workflow.site}
 * Intent: ${workflow.intent.description}
 *
 * To regenerate: imprint emit examples/${workflow.site}/workflow.json --force
 */

import {
  executeWorkflow,
  type CredentialStore,
} from '${runtimeImportPath.replace(/\.ts$/, '.ts')}';
import type { ToolResult, Workflow } from '${pathRel(runtimeImportPath, 'types.ts')}';

const WORKFLOW: Workflow = ${workflowJson};

export interface ${pascalCase(workflow.toolName)}Input {
${paramTypeFields}
}

export async function ${camelCase(workflow.toolName)}(
  input: ${pascalCase(workflow.toolName)}Input,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch } = {},
): Promise<ToolResult> {
  const params: Record<string, string | number | boolean> = {
${defaultsBlock || requiredCopies || '    // (no parameters)'}
${defaultsBlock && requiredCopies ? requiredCopies : ''}
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
  });
}

export { WORKFLOW };
`;
}

function pascalCase(s: string): string {
  return s
    .split(/[_-]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join('');
}

function camelCase(s: string): string {
  const pc = pascalCase(s);
  return pc.charAt(0).toLowerCase() + pc.slice(1);
}

function escapeJsdoc(s: string): string {
  return s.replace(/\*\//g, '*\\/');
}

function pathRel(from: string, sibling: string): string {
  return from.replace(/[^/]+$/, sibling);
}
