/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_flight_booking_options
 * Site: google-flights
 * Intent: Get fare details and booking providers for a selected flight itinerary.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/get_flight_booking_options/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_flight_booking_options",
  "intent": {
    "description": "Get fare details and booking providers for a selected flight itinerary.",
    "userSaid": "Clicked selected one-way, round-trip, and multi-city fares to view fare and booking details."
  },
  "parameters": [
    {
      "name": "trip_type",
      "type": "string",
      "description": "Trip type: one_way, round_trip, or multi_city.",
      "default": "one_way"
    },
    {
      "name": "selected_flights",
      "type": "string",
      "description": "Fresh selection_data JSON emitted by search_flights.",
      "sourcedFrom": {
        "tool": "search_flights",
        "field": "selection_data"
      }
    },
    {
      "name": "adults",
      "type": "number",
      "description": "Number of adult passengers.",
      "default": 1
    },
    {
      "name": "children",
      "type": "number",
      "description": "Number of child passengers.",
      "default": 0
    },
    {
      "name": "cabin_class",
      "type": "string",
      "description": "Only economy is supported by the recording.",
      "default": "economy"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/travel.frontend.flights.FlightsFrontendService/GetBookingResults?f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "Referer": "https://www.google.com/travel/flights",
        "X-Same-Domain": "1",
        "sec-ch-ua-full-version": "\"148.0.7778.96\"",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=${param.selected_flights}&trip_type=${param.trip_type}&adults=${param.adults}&children=${param.children}&cabin_class=${param.cabin_class}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights",
    "waitUntil": "domcontentloaded",
    "waitMs": 1500,
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "FdrFJe[^0-9-]{1,40}(-?[0-9]{10,})",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "(boq_travel-frontend-flights-ui_[A-Za-z0-9_.-]+)",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "limitations": [
    {
      "feature": "Non-economy booking cabins",
      "reason": "The recordings and producer-consumer live chain ground economy only.",
      "omittedParameters": []
    }
  ]
};

export interface GetFlightBookingOptionsInput {
  /** Trip type: one_way, round_trip, or multi_city. */
  trip_type?: string;
  /** Fresh selection_data JSON emitted by search_flights. */
  selected_flights: string;
  /** Number of adult passengers. */
  adults?: number;
  /** Number of child passengers. */
  children?: number;
  /** Only economy is supported by the recording. */
  cabin_class?: string;
}

export async function getFlightBookingOptions(
  input: GetFlightBookingOptionsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    trip_type: input.trip_type ?? "one_way",
    adults: input.adults ?? 1,
    children: input.children ?? 0,
    cabin_class: input.cabin_class ?? "economy",
    selected_flights: input.selected_flights,
  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
