/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_low_fare_calendar
 * Site: southwest
 * Intent: Get Southwest low-fare calendar prices for a route and month.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/get_low_fare_calendar/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_low_fare_calendar",
  "intent": {
    "description": "Get Southwest low-fare calendar prices for a route and month.",
    "userSaid": "i just specified the departure and arrival airports (SJC and SAN) i set teh depart date now i changed to one way trip only now i clicked search now i clicked hte low fare calendar"
  },
  "parameters": [
    {
      "name": "origination_airport_code",
      "type": "string",
      "description": "Origin airport code, such as SJC.",
      "default": "SJC",
      "verified": false,
      "verifyNote": "waived-bot"
    },
    {
      "name": "destination_airport_code",
      "type": "string",
      "description": "Destination airport code, such as SAN.",
      "default": "SAN",
      "verified": false,
      "verifyNote": "waived-bot"
    },
    {
      "name": "departure_date",
      "type": "string",
      "description": "Calendar month anchor date in YYYY-MM-DD format.",
      "default": "2026-09-01",
      "verified": false,
      "verifyNote": "waived-bot"
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "required": true,
          "capability": "ordinary_http",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\\\"]+)\"",
          "group": 1
        }
      ],
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.southwest.com/api/air-booking/v1/air-booking/page/air/low-fare-calendar/select-dates",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "x-api-key": "${state.southwest_api_key}",
        "x-app-id": "air-low-fare-calendar-v2",
        "x-app-version": "9.0.1",
        "x-channel-id": "southwest",
        "x-user-experience-id": "${generated.uuid}",
        "x-diagnostic": "{\"spa\":\"9.0.1\"}",
        "Referer": "https://www.southwest.com/air/low-fare-calendar/select-dates?adultPassengersCount=1&adultsCount=1&currencyCode=USD&departureDate=${param.departure_date}&destinationAirportCode=${param.destination_airport_code}&hasNearByAirport=false&lapInfantPassengersCount=0&originationAirportCode=${param.origination_airport_code}&passengerType=ADULT&promoCode=&returnAirportCode=&returnDate=&selectedFlight1=${param.departure_date}&selectedFlight2=&tripType=oneway&clk=6403032&cbid=6403032"
      },
      "body": "{\"adultPassengersCount\":\"1\",\"adultsCount\":\"1\",\"currencyCode\":\"USD\",\"departureDate\":\"${param.departure_date}\",\"destinationAirportCode\":\"${param.destination_airport_code}\",\"hasNearByAirport\":\"false\",\"lapInfantPassengersCount\":\"0\",\"originationAirportCode\":\"${param.origination_airport_code}\",\"passengerType\":\"ADULT\",\"promoCode\":\"\",\"returnAirportCode\":\"\",\"returnDate\":\"\",\"selectedFlight1\":\"${param.departure_date}\",\"selectedFlight2\":\"\",\"tripType\":\"oneway\",\"clk\":\"6403032\",\"cbid\":\"6403032\"}",
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts",
  "liveVerified": false,
  "liveVerifiedWaiver": {
    "kind": "waived-bot",
    "firstError": "FORBIDDEN in 152ms — escalating",
    "exhaustedBackends": [
      "fetch",
      "cdp-replay",
      "stealth-fetch"
    ]
  }
};

export interface GetLowFareCalendarInput {
  /** Origin airport code, such as SJC. */
  origination_airport_code?: string;
  /** Destination airport code, such as SAN. */
  destination_airport_code?: string;
  /** Calendar month anchor date in YYYY-MM-DD format. */
  departure_date?: string;
}

export async function getLowFareCalendar(
  input: GetLowFareCalendarInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    origination_airport_code: input.origination_airport_code ?? "SJC",
    destination_airport_code: input.destination_airport_code ?? "SAN",
    departure_date: input.departure_date ?? "2026-09-01",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
