/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_low_fare_calendar
 * Site: southwest
 * Intent: Find Southwest's lowest fares by date for a route and month.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/get_low_fare_calendar/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_low_fare_calendar",
  "intent": {
    "description": "Find Southwest's lowest fares by date for a route and month.",
    "userSaid": "Specified SJC to SAN, set the departure date, chose a one-way trip, searched, and opened the low fare calendar."
  },
  "parameters": [
    {
      "name": "origination_airport_code",
      "type": "string",
      "description": "Three-letter departure airport code.",
      "default": "SJC",
      "verified": true
    },
    {
      "name": "destination_airport_code",
      "type": "string",
      "description": "Three-letter arrival airport code.",
      "default": "SAN",
      "verified": true
    },
    {
      "name": "departure_date",
      "type": "string",
      "description": "Date or month anchor in YYYY-MM-DD format.",
      "default": "2026-09-01",
      "verified": true
    },
    {
      "name": "return_date",
      "type": "string",
      "description": "Optional return-date anchor for round trips.",
      "default": "",
      "verified": true
    },
    {
      "name": "trip_type",
      "type": "string",
      "description": "Trip type, such as oneway or roundtrip.",
      "default": "oneway",
      "verified": true
    },
    {
      "name": "adults_count",
      "type": "number",
      "description": "Number of adult passengers.",
      "default": 1,
      "verified": false,
      "verifyNote": "semantic-gap"
    },
    {
      "name": "lap_infant_passengers_count",
      "type": "number",
      "description": "Number of lap-infant passengers.",
      "default": 0,
      "verified": false,
      "verifyNote": "semantic-gap"
    },
    {
      "name": "currency_code",
      "type": "string",
      "description": "Currency code for displayed fares, such as USD.",
      "default": "USD",
      "verified": false,
      "verifyNote": "semantic-gap"
    },
    {
      "name": "promo_code",
      "type": "string",
      "description": "Optional promotional code.",
      "default": "",
      "verified": false,
      "verifyNote": "semantic-gap"
    },
    {
      "name": "include_nearby_airports",
      "type": "boolean",
      "description": "Whether nearby airports should be considered.",
      "default": false,
      "verified": false,
      "verifyNote": "semantic-gap"
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "required": true,
          "capability": "ordinary_http",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\\\"]+)\"",
          "group": 1
        }
      ],
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.southwest.com/api/air-booking/v1/air-booking/page/air/low-fare-calendar/select-dates",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "Origin": "https://www.southwest.com",
        "Referer": "https://www.southwest.com/air/low-fare-calendar/select-dates",
        "x-api-key": "${state.southwest_api_key}",
        "x-app-id": "air-low-fare-calendar-v2",
        "x-app-version": "9.0.1",
        "x-channel-id": "southwest",
        "x-user-experience-id": "${generated.uuid}",
        "x-diagnostic": "{\"spa\":\"9.0.1\"}"
      },
      "body": "{\"adultPassengersCount\":\"${param.adults_count}\",\"adultsCount\":\"${param.adults_count}\",\"currencyCode\":\"${param.currency_code}\",\"departureDate\":\"${param.departure_date}\",\"destinationAirportCode\":\"${param.destination_airport_code}\",\"hasNearByAirport\":\"${param.include_nearby_airports}\",\"lapInfantPassengersCount\":\"${param.lap_infant_passengers_count}\",\"originationAirportCode\":\"${param.origination_airport_code}\",\"passengerType\":\"ADULT\",\"promoCode\":\"${param.promo_code}\",\"returnAirportCode\":\"\",\"returnDate\":\"${param.return_date}\",\"selectedFlight1\":\"${param.departure_date}\",\"selectedFlight2\":\"${param.return_date}\",\"tripType\":\"${param.trip_type}\",\"clk\":\"6403032\",\"cbid\":\"6403032\"}",
      "bodyPlaceholderEncoding": "json-string",
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts",
  "liveVerified": true
};

export interface GetLowFareCalendarInput {
  /** Three-letter departure airport code. */
  origination_airport_code?: string;
  /** Three-letter arrival airport code. */
  destination_airport_code?: string;
  /** Date or month anchor in YYYY-MM-DD format. */
  departure_date?: string;
  /** Optional return-date anchor for round trips. */
  return_date?: string;
  /** Trip type, such as oneway or roundtrip. */
  trip_type?: string;
  /** Number of adult passengers. */
  adults_count?: number;
  /** Number of lap-infant passengers. */
  lap_infant_passengers_count?: number;
  /** Currency code for displayed fares, such as USD. */
  currency_code?: string;
  /** Optional promotional code. */
  promo_code?: string;
  /** Whether nearby airports should be considered. */
  include_nearby_airports?: boolean;
}

export async function getLowFareCalendar(
  input: GetLowFareCalendarInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    origination_airport_code: input.origination_airport_code ?? "SJC",
    destination_airport_code: input.destination_airport_code ?? "SAN",
    departure_date: input.departure_date ?? "2026-09-01",
    return_date: input.return_date ?? "",
    trip_type: input.trip_type ?? "oneway",
    adults_count: input.adults_count ?? 1,
    lap_infant_passengers_count: input.lap_infant_passengers_count ?? 0,
    currency_code: input.currency_code ?? "USD",
    promo_code: input.promo_code ?? "",
    include_nearby_airports: input.include_nearby_airports ?? false,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
