/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: get_flight_location_details
 * Site: google-flights
 * Intent: Resolve a selected Google Flights airport code or city entity identifier into canonical location metadata.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/get_flight_location_details/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type BrowserNavigationTransport,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "get_flight_location_details",
  "intent": {
    "description": "Resolve a selected Google Flights airport code or city entity identifier into canonical location metadata.",
    "userSaid": "Resolve a selected airport or city identifier into detailed flight-location metadata."
  },
  "parameters": [
    {
      "name": "location_id",
      "type": "string",
      "description": "Selected three-letter airport code or slash-prefixed Google city entity identifier to resolve.",
      "verified": true,
      "sourcedFrom": {
        "tool": "search_flight_locations",
        "field": "location_id"
      }
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/batchexecute?rpcids=tDoGIe&source-path=%2Ftravel%2Fflights&f.sid=${state.f_sid}&bl=${state.bl}&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=${generated.epoch_ms}&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "X-Same-Domain": "1",
        "Referer": "https://www.google.com/travel/flights",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=${param.location_id}",
      "effect": "safe"
    }
  ],
  "site": "google-flights",
  "bootstrap": {
    "url": "https://www.google.com/travel/flights",
    "waitUntil": "domcontentloaded",
    "captures": [
      {
        "name": "f_sid",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "[\"']FdrFJe[\"']\\s*:\\s*[\"'](-?\\d+)[\"']",
        "group": 1
      },
      {
        "name": "bl",
        "required": true,
        "capability": "browser_bootstrap",
        "source": "html_regex",
        "pattern": "[\"']cfb2h[\"']\\s*:\\s*[\"']([^\"']+)[\"']",
        "group": 1
      }
    ]
  },
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts",
  "liveVerified": true
};

export interface GetFlightLocationDetailsInput {
  /** Selected three-letter airport code or slash-prefixed Google city entity identifier to resolve. */
  location_id: string;
}

export async function getFlightLocationDetails(
  input: GetFlightLocationDetailsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; browser?: BrowserNavigationTransport; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    location_id: input.location_id,

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    browser: opts.browser,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
