/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: search_google_flights
 * Site: google-flights
 * Intent: Search Google Flights for round-trip flights between two airports on specific dates.
 *
 * To regenerate: imprint emit ~/.imprint/google-flights/search_google_flights/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "search_google_flights",
  "intent": {
    "description": "Search Google Flights for round-trip flights between two airports on specific dates.",
    "userSaid": "i searched for a sample flight the default mode is economy (include basic) now i changed to economy (exclude basic) now i searched for premium economy now i searched for business now i searched for first class now im going to start messing with all the filters available i played with all the filters now i clicked one of the departure flights, and now it's showing me a list of the return flights i selected the return flight, and now it's showing me the booking options"
  },
  "parameters": [
    {
      "name": "origin_airport",
      "type": "string",
      "description": "Origin airport IATA code.",
      "default": "SJC"
    },
    {
      "name": "destination_airport",
      "type": "string",
      "description": "Destination airport IATA code.",
      "default": "SAN"
    },
    {
      "name": "depart_date",
      "type": "string",
      "description": "Outbound departure date in YYYY-MM-DD format.",
      "default": "2026-07-10"
    },
    {
      "name": "return_date",
      "type": "string",
      "description": "Return departure date in YYYY-MM-DD format.",
      "default": "2026-07-16"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "https://www.google.com/_/FlightsFrontendUi/data/travel.frontend.flights.FlightsFrontendService/GetShoppingResults?f.sid=-1290970187393889182&bl=boq_travel-frontend-flights-ui_20260506.02_p0&hl=en-US&soc-app=162&soc-platform=1&soc-device=1&_reqid=4008662&rt=c",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "Referer": "https://www.google.com/travel/flights",
        "X-Same-Domain": "1",
        "x-goog-ext-259736195-jspb": "[\"en-US\",\"US\",\"USD\",2,null,[420],null,null,7,[]]"
      },
      "body": "f.req=%5Bnull%2C%22%5B%5B%5D%2C%5Bnull%2Cnull%2C1%2Cnull%2C%5B%5D%2C1%2C%5B1%2C0%2C0%2C0%5D%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C%5B%5B%5B%5B%5B%5C%22${param.origin_airport}%5C%22%2C0%5D%5D%5D%2C%5B%5B%5B%5C%22${param.destination_airport}%5C%22%2C0%5D%5D%5D%2Cnull%2C0%2Cnull%2Cnull%2C%5C%22${param.depart_date}%5C%22%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C690%2Cnull%2C3%5D%2C%5B%5B%5B%5B%5C%22${param.destination_airport}%5C%22%2C0%5D%5D%5D%2C%5B%5B%5B%5C%22${param.origin_airport}%5C%22%2C0%5D%5D%5D%2Cnull%2C0%2Cnull%2Cnull%2C%5C%22${param.return_date}%5C%22%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C690%2Cnull%2C3%5D%5D%2Cnull%2Cnull%2Cnull%2C1%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C0%5D%2C0%2C0%2C0%2C1%5D%22%5D&"
    }
  ],
  "site": "google-flights",
  "parserModule": "./parser.ts"
};

export interface SearchGoogleFlightsInput {
  /** Origin airport IATA code. */
  origin_airport?: string;
  /** Destination airport IATA code. */
  destination_airport?: string;
  /** Outbound departure date in YYYY-MM-DD format. */
  depart_date?: string;
  /** Return departure date in YYYY-MM-DD format. */
  return_date?: string;
}

export async function searchGoogleFlights(
  input: SearchGoogleFlightsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    origin_airport: input.origin_airport ?? "SJC",
    destination_airport: input.destination_airport ?? "SAN",
    depart_date: input.depart_date ?? "2026-07-10",
    return_date: input.return_date ?? "2026-07-16",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
