/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: search_flights
 * Site: southwest
 * Intent: Search Southwest one-way or round-trip flight times and fares for a route and date.
 *
 * To regenerate: imprint emit ~/.imprint/southwest/search_flights/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "search_flights",
  "intent": {
    "description": "Search Southwest one-way or round-trip flight times and fares for a route and date.",
    "userSaid": "i just specified the departure and arrival airports (SJC and SAN) i set teh depart date now i changed to one way trip only now i clicked search"
  },
  "parameters": [
    {
      "name": "origination_airport_code",
      "type": "string",
      "description": "Origin airport code, such as SJC.",
      "default": "SJC"
    },
    {
      "name": "destination_airport_code",
      "type": "string",
      "description": "Destination airport code, such as SAN.",
      "default": "SAN"
    },
    {
      "name": "departure_date",
      "type": "string",
      "description": "Outbound departure date in YYYY-MM-DD format.",
      "default": "2026-08-20"
    },
    {
      "name": "return_date",
      "type": "string",
      "description": "Return date in YYYY-MM-DD format for round trips; empty for one-way searches.",
      "default": ""
    },
    {
      "name": "trip_type",
      "type": "string",
      "description": "Trip type, oneway or roundtrip.",
      "default": "oneway"
    },
    {
      "name": "adults_count",
      "type": "number",
      "description": "Number of adult passengers.",
      "default": 1
    },
    {
      "name": "fare_type",
      "type": "string",
      "description": "Fare currency type: USD for dollars, POINTS for Rapid Rewards points.",
      "default": "USD"
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.southwest.com/swa-ui/bootstrap/landing-home-page-v2/1/data.js",
      "headers": {
        "Accept": "application/javascript, text/javascript, */*; q=0.01"
      },
      "captures": [
        {
          "name": "southwest_api_key",
          "required": true,
          "capability": "ordinary_http",
          "source": "text_regex",
          "pattern": "\"swa-bootstrap-landing-home-page-v2/api-keys\":\\[function\\(require,module,exports\\)\\{\\s*module\\.exports = \\{[^}]*\"prod\":\"([^\"]+)\"",
          "group": 1
        }
      ],
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.southwest.com/api/air-booking/v1/air-booking/page/air/booking/shopping",
      "headers": {
        "Accept": "application/json, text/javascript, */*; q=0.01",
        "Content-Type": "application/json",
        "X-API-Key": "${state.southwest_api_key}",
        "X-App-ID": "air-booking",
        "X-Channel-ID": "southwest",
        "X-User-Experience-ID": "${generated.uuid}",
        "Referer": "https://www.southwest.com/air/booking/select-depart.html?adultsCount=${param.adults_count}&adultPassengersCount=${param.adults_count}&destinationAirportCode=${param.destination_airport_code}&departureDate=${param.departure_date}&departureTimeOfDay=ALL_DAY&fareType=${param.fare_type}&int=HOMEQBOMAIR&originationAirportCode=${param.origination_airport_code}&passengerType=ADULT&promoCode=&returnDate=${param.return_date}&returnTimeOfDay=ALL_DAY&tripType=${param.trip_type}"
      },
      "body": "{\"adultPassengersCount\":\"${param.adults_count}\",\"adultsCount\":\"${param.adults_count}\",\"departureDate\":\"${param.departure_date}\",\"departureTimeOfDay\":\"ALL_DAY\",\"destinationAirportCode\":\"${param.destination_airport_code}\",\"fareType\":\"${param.fare_type}\",\"int\":\"HOMEQBOMAIR\",\"originationAirportCode\":\"${param.origination_airport_code}\",\"passengerType\":\"ADULT\",\"promoCode\":\"\",\"returnDate\":\"${param.return_date}\",\"returnTimeOfDay\":\"ALL_DAY\",\"tripType\":\"${param.trip_type}\",\"application\":\"air-booking\",\"site\":\"southwest\"}",
      "effect": "safe"
    }
  ],
  "site": "southwest",
  "parserModule": "./parser.ts"
};

export interface SearchFlightsInput {
  /** Origin airport code, such as SJC. */
  origination_airport_code?: string;
  /** Destination airport code, such as SAN. */
  destination_airport_code?: string;
  /** Outbound departure date in YYYY-MM-DD format. */
  departure_date?: string;
  /** Return date in YYYY-MM-DD format for round trips; empty for one-way searches. */
  return_date?: string;
  /** Trip type, oneway or roundtrip. */
  trip_type?: string;
  /** Number of adult passengers. */
  adults_count?: number;
  /** Fare currency type: USD for dollars, POINTS for Rapid Rewards points. */
  fare_type?: string;
}

export async function searchFlights(
  input: SearchFlightsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    origination_airport_code: input.origination_airport_code ?? "SJC",
    destination_airport_code: input.destination_airport_code ?? "SAN",
    departure_date: input.departure_date ?? "2026-08-20",
    return_date: input.return_date ?? "",
    trip_type: input.trip_type ?? "oneway",
    adults_count: input.adults_count ?? 1,
    fare_type: input.fare_type ?? "USD",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
