/**
 * GENERATED by `imprint emit` — DO NOT EDIT BY HAND.
 *
 * Tool: search_namecheap_domains
 * Site: namecheap-domains
 * Intent: Search Namecheap for available domains matching a query, returning the exact-match availability + pricing, suggested domain picks across many TLDs, the TLD catalog, and Spaceship/brandstore aftermarket marketplace listings.
 *
 * To regenerate: imprint emit ~/.imprint/namecheap-domains/search_namecheap_domains/workflow.json --force
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  executeWorkflow,
  type CredentialStore,
} from 'imprint/runtime';
import type { ToolResult, Workflow } from 'imprint/types';

const WORKFLOW: Workflow = {
  "toolName": "search_namecheap_domains",
  "intent": {
    "description": "Search Namecheap for available domains matching a query, returning the exact-match availability + pricing, suggested domain picks across many TLDs, the TLD catalog, and Spaceship/brandstore aftermarket marketplace listings.",
    "userSaid": "i searched for imprint on namecheap. njow there are a lot of filters, by default i am on \"Popular\". there were about 30 filters. i cycled through all of them"
  },
  "parameters": [
    {
      "name": "query",
      "type": "string",
      "description": "The SLD (second-level-domain) or search term to look up (e.g. 'imprint').",
      "default": "imprint"
    },
    {
      "name": "category",
      "type": "string",
      "description": "Optional TLD category filter to narrow returned suggestions. One of the CategoryName values exposed by the TLD catalog: 'popular', 'international', 'new', '088domains'. Leave empty for unfiltered results.",
      "default": ""
    }
  ],
  "requests": [
    {
      "method": "GET",
      "url": "https://www.namecheap.com/domains/tlds.ashx",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.namecheap.com/domains/registration/results/?domain=${param.query}",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
        "sec-ch-ua": "\"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"8\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\""
      },
      "effect": "safe"
    },
    {
      "method": "GET",
      "url": "https://rtb.namecheapapi.com/api/search/${param.query}?session_id=1000000000000&search=false",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Origin": "https://www.namecheap.com",
        "Referer": "https://www.namecheap.com/",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
        "sec-ch-ua": "\"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"8\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\""
      },
      "effect": "safe"
    },
    {
      "method": "GET",
      "url": "https://rtb.namecheapapi.com/api/picks/${param.query}?session_id=1000000000000",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Origin": "https://www.namecheap.com",
        "Referer": "https://www.namecheap.com/",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
        "sec-ch-ua": "\"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"8\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\""
      },
      "effect": "safe"
    },
    {
      "method": "POST",
      "url": "https://www.namecheap.com/api/v1/ncpl/domainsearchgateway/domain/readBySld",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Content-Type": "application/json; charset=UTF-8",
        "Origin": "https://www.namecheap.com",
        "Referer": "https://www.namecheap.com/domains/registration/results/?domain=${param.query}",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
        "X-Requested-With": "XMLHttpRequest",
        "sec-ch-ua": "\"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"8\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\""
      },
      "body": "{\"request\":{\"sld\":\"${param.query}\",\"sources\":[\"sellerhub\",\"brandstore\"]}}",
      "effect": "safe"
    },
    {
      "method": "GET",
      "url": "https://domains.revved.com/v1/domainStatus?whois=true&domains=__PLACEHOLDER__",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://www.namecheap.com/"
      },
      "effect": "safe"
    }
  ],
  "site": "namecheap-domains",
  "parserModule": "./parser.ts",
  "requestTransformModule": "./request-transform.ts"
};

export interface SearchNamecheapDomainsInput {
  /** The SLD (second-level-domain) or search term to look up (e.g. 'imprint'). */
  query?: string;
  /** Optional TLD category filter to narrow returned suggestions. One of the CategoryName values exposed by the TLD catalog: 'popular', 'international', 'new', '088domains'. Leave empty for unfiltered results. */
  category?: string;
}

export async function searchNamecheapDomains(
  input: SearchNamecheapDomainsInput,
  opts: { credentials?: CredentialStore; fetchImpl?: typeof fetch; initialState?: Record<string, unknown> } = {},
): Promise<ToolResult> {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const params: Record<string, string | number | boolean> = {
    query: input.query ?? "imprint",
    category: input.category ?? "",

  };
  return executeWorkflow({
    workflow: WORKFLOW,
    params,
    credentials: opts.credentials,
    fetchImpl: opts.fetchImpl,
    initialState: opts.initialState,
    workflowPath: join(__dirname, 'workflow.json'),
  });
}

export { WORKFLOW };
